# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heighliner < Formula
  desc "Heighliner is an application development platform with the state-of-the-art cloud native stacks"
  homepage "https://github.com/h8r-dev/heighliner"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://dl.h8r.io/hln/releases/0.1.0/heighliner_v0.1.0_darwin_arm64.tar.gz"
      sha256 "b0ce45c4920cf7073fdfe6cb9d3b7b8620c2b42944ad63c46cae7d2b84d3453e"

      def install
        bin.install "hln"
      end
    end
    if Hardware::CPU.intel?
      url "https://dl.h8r.io/hln/releases/0.1.0/heighliner_v0.1.0_darwin_amd64.tar.gz"
      sha256 "3bcd3f63155c72935223fca387d90f8cb45a37d363bfeb01186724bf41b924f7"

      def install
        bin.install "hln"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://dl.h8r.io/hln/releases/0.1.0/heighliner_v0.1.0_linux_amd64.tar.gz"
      sha256 "47ca85d8156bd3254b4a02884c0e310961a0feadc2fef9078aadb25c0a0d2e9d"

      def install
        bin.install "hln"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.h8r.io/hln/releases/0.1.0/heighliner_v0.1.0_linux_arm64.tar.gz"
      sha256 "8998e92b4049c22238d702cbaa7d7f23490faaf8f624955a35b111ef24675f7c"

      def install
        bin.install "hln"
      end
    end
  end

  test do
    system "#{bin}/hln version"
  end
end
